//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetManager
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
